routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('home', 'HomeController@index')->name('home');
Route::get('products', 'HomeController@shop')->name('shop');
Route::get('products/{product}', 'HomeController@details')->name('product.details');
Route::get('categories/{category}', 'HomeController@category')->name('product.category');

Route::get('contact', function (){
    return view('front.contact');
})->name('contact');

Auth::routes(['reset' => false]);

Route::prefix('cart')->group(function (){
    Route::get('/', 'CartController@index')->name('cart');

    Route::get('addItem/{product}', 'CartController@addItem')->name('cart.add');

    Route::get('remove/{product}', 'CartController@destroy')->name('cart.remove');

    Route::get('clear', 'CartController@clear')->name('cart.clear');

    Route::post('update', 'CartController@update')->name('cart.update');
});

Route::prefix('admin')->middleware(['auth', 'admin'])->group(function (){
    Route::get('/', function (){
        return view('admin.index');
    })->name('admin.index');

    Route::resource('products', 'ProductController');
    Route::resource('categories', 'CategoryController');

    Route::get('orders', 'OrderController@index')->name('orders.index');
    Route::post('orders/{order}', 'OrderController@confirm')->name('orders.confirm');
    Route::put('orders/{order}', 'OrderController@cancel')->name('orders.cancel');

    Route::post('discount/add/{product}', 'DiscountController@apply')->name('discount.apply');
    Route::post('discount/delete/{product}', 'DiscountController@cancel')->name('discount.cancel');
});


Route::middleware('auth')->group(function (){
    Route::get('checkout', 'CheckoutController@index')->name('checkout');
    Route::post('validate', 'CheckoutController@formValidate')->name('checkout-validate');
    Route::get('thankyou', function (){
        return view('profile.thankyou');
    });
    Route::prefix('profile')->group(function (){
        Route::get('/', 'ProfileController@index')->name('profile');
        Route::get('orders', 'ProfileController@orders')->name('profile.orders');
        Route::get('address', 'ProfileController@address')->name('profile.address');
        Route::post('updateAddress', 'ProfileController@updateAddress')->name('profile.updateAddress');
        Route::get('password', 'ProfileController@password')->name('profile.password');
        Route::post('updatePassword', 'ProfileController@updatePassword')->name('profile.updatePassword');
    });
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';
    protected $primaryKey = 'id';
    protected $fillable = [
        'name', 'code', 'price', 'image', 'info', 'spl_price', 'category_id', 'discount'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use Illuminate\Http\Request;


class ProductController extends Controller
{
    public function index()
    {
        return view('admin.product.index', ['products' => Product::latest()->get()]);
    }

    public function create()
    {
        return view('admin.product.form',[
            'categories' => Category::all(),
        ]);
    }

    public function store(Request $request)
    {
        $formInput = $request->except('image');

        $request->validate([
            'name' => 'required|unique:products',
            'code' => 'required|unique:products',
            'category_id' => 'required',
            'price' => 'required',
            'info' => 'required',
            'image' => 'image|mimes:png,jpg,jpeg|max:10000',
        ]);

        $image = $request->image;


        if ($image){
            $imageName = $image->getClientOriginalName();
            $image->move('images', $imageName);
            $formInput['image'] = $imageName;
        }

        Product::create($formInput);

        return redirect()->route('products.index')->with('message', 'Товар сохранен успешно');
    }

    public function show(Product $product)
    {
        return view('admin.product.show', ['product' => $product]);
    }

    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->route('products.index')->with('message', 'Товар удален успешно');
    }

    public function edit(Product $product)
    {
        return view('admin.product.form', [
            'product' => $product,
            'categories' => Category::all(),
        ]);
    }

    public function update(Request $request, Product $product)
    {
        $formInput = $request->except('image');

        $request->validate([
            'name' => 'required|unique:products,name,' . $product->id . ',id',
            'code' => 'required|unique:products,code,' . $product->id . ',id',
            'category_id' => 'required',
            'price' => 'required',
            'info' => 'required',
            'image' => 'image|mimes:png,jpg,jpeg|max:10000',
        ]);

        $image = $request->image ?? null;

        if ($image){
            $imageName = $image->getClientOriginalName();
            $image->move('images', $imageName);
            $formInput['image'] = $imageName;
        }

        $product->update($formInput);

        return redirect()->route('products.index')->with('message', 'Товар отредактирован успешно');
    }
}

resources/views/admin/product/form.blade.php
@extends('adminlte::page')

@section('title', 'AdminPanel')

@section('content_header')
    <h1>Добавление/редактирование товара</h1>
@stop

@section('content')
    <div class="container-fluid">
        <div class="row">
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                    <div class="col-md-6">
                        <div class="panel-body">
                            @if(isset($product))
                                <form method="POST" action="{{route('products.update', $product->id)}}" enctype="multipart/form-data">
                                    @method('PUT')
                            @else
                                <form method="POST" action="{{route('products.store')}}" enctype="multipart/form-data">
                            @endif
                                @csrf
                                <div class="form-group">
                                    <label for="name">Наименование</label>
                                    <input class="form-control" required="" minlength="5" name="name" type="text" id="name" value="{{old('name', $product->name ?? null)}}">
                                </div>

                                <div class="form-group">
                                    <label for="code">Код</label>
                                    <input class="form-control" name="code" type="text" id="code" value="{{old('code', $product->code ?? null)}}">
                                </div>

                                <div class="form-group">
                                    <label for="price">Цена</label>
                                    <input class="form-control" name="price" type="text" id="price" value="{{old('price', $product->price ?? null)}}">
                                </div>

                                <div class="form-group">
                                    <label for="info">Описание</label>
                                    <input class="form-control" name="info" type="text" id="info" value="{{old('info', $product->info ?? null)}}">
                                </div>

                                <div class="form-group">
                                    <label for="image">Изображение</label>
                                    <input class="form-control" name="image" type="file" id="image">
                                </div>

                                <div class="form-group">
                                    <label for="category">Категория</label>
                                    <select class="form-control" name="category_id">
                                        @forelse($categories as $category)
                                            <option @if(isset($product))
                                                        @if($product->category_id == $category->id) selected @endif
                                                    @endif value="{{ $category->id }}">{{ $category->name }}</option>
                                        @empty
                                            <option></option>
                                        @endforelse
                                    </select>
                                </div>

                                <div class="form-group">
                                    <img src="{{url('images', $product->image ?? 'product01.png')}}" width="200" alt="Отсутствует">
                                </div>

                                <input class="btn btn-primary" type="submit" value="Сохранить">
                            </form>
                        </div>
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                    </div>
            </main>
        </div>
    </div>
@stop

resources/views/admin/product/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminPanel')

@section('content_header')
    <h1 class="product-title">Все товары</h1>
@stop

@section('content')
    @if (session('message'))
        <div class="alert alert-warning">
            {{ session('message') }}
        </div>
    @endif

    <a href="{{route('products.create')}}" type="button" class="btn btn-success">Добавить товар</a>
    <a href="{{route('categories.create')}}" type="button" class="btn btn-primary">Создать категорию</a>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Изображение</th>
            <th>Наименование</th>
            <th>Информация</th>
            <th>Категория</th>
            <th>Цена, руб.</th>
            <th>Акция</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @forelse($products as $product)
            <tr>
                <td>{{$product->id}}</td>
                <td><img src="{{url('images', $product->image ?? 'product01.png')}}" width="100" alt="Отсутствует"></td>
                <td>{{$product->name}}</td>
                <td>{{$product->info}}</td>
                <td>{{$product->category->name ?? '!!!категория отсутствует!!!'}}</td>
                <td>{{$product->price}}</td>
                <td>
                    @if($product->discount == 'valid')
                        Да
                    @endif
                </td>
                <td>
                    @if($product->discount == 'valid')
                        <form action="{{route('discount.cancel', $product->id)}}" method="POST">
                            @csrf
                            <button class="btn btn-secondary btn-sm">Убрать акцию</button>
                        </form>
                    @else
                        <form action="{{route('discount.apply', $product->id)}}" method="POST">
                            @csrf
                            <button class="btn btn-warning btn-sm">В акцию</button>
                        </form>
                    @endif

                </td>
                <td>
                    <form action="{{route('products.destroy', $product->id)}}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button class="btn btn-danger btn-sm">Удалить</button>
                    </form>
                </td>
                <td>
                    <a class="btn btn-info btn-sm" href="{{route('products.edit', $product->id)}}">Редактировать</a>
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="10">Нет товаров</td>
            </tr>
        @endforelse

        </tbody>
    </table>
@stop